version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: postgreDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports: 
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  nats-streaming:
    image: nats-streaming:latest
    container_name: nats_container
    ports:
      - "4222:4222"
      - "8222:8222"

  test-container:
    build: ./
    container_name: dockerdev
    depends_on:
      - postgres
      - nats-streaming
    ports:
      - "8080:8080"
      - "4000:4000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./config.yaml:/app/config.yaml
    command: ["/dlv", "--listen=:4000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/server"]

  postgres-cache:
    image: postgres:latest
    container_name: postgres_cache_container
    environment:
      POSTGRES_DB: cacheDB
      POSTGRES_USER: cacheUser
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - ./cache-init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_cache_data:/var/lib/postgresql/data
    command: ["-c", "hba_file=/var/lib/postgresql/data/pg_hba.conf"]

volumes:
  postgres_data:
  postgres_cache_data:
